build-and-push-helm-chart:
    name: Build and Push Helm Chart
    runs-on: ubuntu-latest
    needs: [build-and-publish-docker-image]
    steps:
    # Checkout the repo
    - uses: actions/checkout@master

    - name: Helm Install
      uses: azure/setup-helm@v1

    - name: Helm Repo Add
      run: |
        helm repo add ${{ env.containerRegistryName }} https://${{ env.containerRegistry }}/helm/v1/repo --username ${{ secrets.ACR_USERNAME }} --password ${{ secrets.ACR_PASSWORD }}
      env:
        HELM_EXPERIMENTAL_OCI: 1

    - name: Helm Chart Save
      run: |
        cd ./content-web/charts/web

        helm chart save . content-web:v${{ env.tag }}
        helm chart save . ${{ env.containerRegistry }}/helm/content-web:v${{ env.tag }}

        # list out saved charts
        helm chart list
      env:
        HELM_EXPERIMENTAL_OCI: 1

    - name: Helm Chart Push
      run: |
        helm registry login ${{ env.containerRegistry }} --username ${{ secrets.ACR_USERNAME }} --password ${{ secrets.ACR_PASSWORD }}
        helm chart push ${{ env.containerRegistry }}/helm/content-web:v${{ env.tag }}
      env:
        HELM_EXPERIMENTAL_OCI: 1